FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt ./

RUN pip install --upgrade pip \
&& pip3 install -r requirements.txt \
&& useradd -ms /bin/bash api_v2_user

COPY api_v2.py ./

USER api_v2_user 

EXPOSE 8083

CMD ["python3","api_v2.py"]
