FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt ./

RUN pip install --upgrade pip \
&& pip3 install -r requirements.txt \
&& useradd -ms /bin/bash api_v1_user

COPY api_v1.py ./

USER api_v1_user 

EXPOSE 8082

CMD ["python3","code/api_v1.py"]
