FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt ./

RUN pip install --upgrade pip \
&& pip3 install -r requirements.txt \
&& useradd -ms /bin/bash test

COPY code/api_v1.py test.py ./

USER test

CMD ["python3","test.py"]
