FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt ./

RUN pip install --upgrade pip 
RUN pip3 install -r requirements.txt 
RUN useradd -ms /bin/bash api_v2_user
RUN pip3 install requests

#COPY api_v2.py ./

USER api_v2_user 

EXPOSE 8083

CMD ["python3","code/api_v2.py"]
