FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt ./

RUN pip install --upgrade pip 
RUN pip3 install -r requirements.txt 
RUN useradd -ms /bin/bash test
RUN pip3 install requests


#COPY api_v1.py test.py ./

USER test

CMD ["python3","code/test.py"]
